// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RSSVibe.Data;

#nullable disable

namespace RSSVibe.Data.Migrations
{
    [DbContext(typeof(RssVibeDbContext))]
    partial class RssVibeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.Feed", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnalysisId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Etag")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastParseStatus")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastParsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextParseAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedSourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<short>("TtlMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)60);

                    b.Property<string>("UpdateIntervalUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("UpdateIntervalValue")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Selectors", "RSSVibe.Data.Entities.Feed.Selectors#FeedSelectors", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Author");

                            b1.Property<string>("Description");

                            b1.Property<string>("Image");

                            b1.Property<string>("ItemContainer");

                            b1.Property<string>("Link");

                            b1.Property<string>("PublishedDate");

                            b1.Property<string>("Title");

                            b1.ToJson("Selectors");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.HasIndex("NextParseAfter", "LastParseStatus");

                    b.HasIndex("UserId", "NormalizedSourceUrl")
                        .IsUnique();

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.FeedAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AiModel")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AnalysisCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AnalysisStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<Guid?>("ApprovedFeedId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PreflightChecks")
                        .HasColumnType("integer");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("Warnings")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PreflightDetails", "RSSVibe.Data.Entities.FeedAnalysis.PreflightDetails#FeedPreflightDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AdditionalInfo")
                                .IsRequired();

                            b1.Property<string>("ErrorMessage");

                            b1.Property<bool>("HasInvalidMarkup");

                            b1.Property<bool>("IsPaywalled");

                            b1.Property<bool>("IsRateLimited");

                            b1.Property<bool>("RequiresAuthentication");

                            b1.Property<bool>("RequiresJavascript");

                            b1.ToJson("PreflightDetails");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Selectors", "RSSVibe.Data.Entities.FeedAnalysis.Selectors#FeedSelectors", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Author");

                            b1.Property<string>("Description");

                            b1.Property<string>("Image");

                            b1.Property<string>("ItemContainer");

                            b1.Property<string>("Link");

                            b1.Property<string>("PublishedDate");

                            b1.Property<string>("Title");

                            b1.ToJson("Selectors");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AnalysisStatus", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("UserId", "NormalizedUrl")
                        .IsUnique();

                    b.ToTable("FeedAnalyses");
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.FeedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FeedId")
                        .HasColumnType("uuid");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<Guid?>("FirstParseRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastParseRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NormalizedSourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RawMetadata", "RSSVibe.Data.Entities.FeedItem.RawMetadata#FeedItemMetadata", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Author");

                            b1.Property<string>("Category");

                            b1.Property<string>("ContentHash");

                            b1.Property<string>("ImageUrl");

                            b1.Property<string>("Language");

                            b1.PrimitiveCollection<string>("Tags");

                            b1.Property<int?>("WordCount");

                            b1.ToJson("RawMetadata");
                        });

                    b.HasKey("Id");

                    b.HasIndex("FirstParseRunId");

                    b.HasIndex("LastParseRunId");

                    b.HasIndex("FeedId", "Fingerprint")
                        .IsUnique();

                    b.HasIndex("FeedId", "LastSeenAt")
                        .IsDescending(false, true);

                    b.HasIndex("FeedId", "NormalizedSourceUrl")
                        .IsUnique();

                    b.HasIndex("FeedId", "PublishedAt")
                        .IsDescending(false, true);

                    b.ToTable("FeedItems");
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.FeedParseRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<Guid>("FeedId")
                        .HasColumnType("uuid");

                    b.Property<int>("FetchedItemsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<short?>("HttpStatusCode")
                        .HasColumnType("smallint");

                    b.Property<int>("NewItemsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("SkippedItemsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UpdatedItemsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ResponseHeaders", "RSSVibe.Data.Entities.FeedParseRun.ResponseHeaders#HttpResponseHeaders", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CacheControl");

                            b1.Property<int?>("ContentLength");

                            b1.Property<string>("ContentType");

                            b1.Property<string>("ETag");

                            b1.Property<string>("Expires");

                            b1.Property<string>("LastModified");

                            b1.Property<string>("Server");

                            b1.ToJson("ResponseHeaders");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasFilter("\"Status\" = 'failed'");

                    b.HasIndex("FeedId", "StartedAt")
                        .IsDescending(false, true);

                    b.ToTable("FeedParseRuns");
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.FeedParseRunItem", b =>
                {
                    b.Property<Guid>("FeedParseRunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeedItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("FeedParseRunId", "FeedItemId");

                    b.HasIndex("FeedItemId", "SeenAt")
                        .IsDescending(false, true);

                    b.HasIndex("FeedParseRunId", "ChangeKind");

                    b.ToTable("FeedParseRunItems");
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("IX_RefreshTokens_UserId_RevokedAt");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RSSVibe.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RSSVibe.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSSVibe.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RSSVibe.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.Feed", b =>
                {
                    b.HasOne("RSSVibe.Data.Entities.FeedAnalysis", "Analysis")
                        .WithOne("ApprovedFeed")
                        .HasForeignKey("RSSVibe.Data.Entities.Feed", "AnalysisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RSSVibe.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.FeedAnalysis", b =>
                {
                    b.HasOne("RSSVibe.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.FeedItem", b =>
                {
                    b.HasOne("RSSVibe.Data.Entities.Feed", "Feed")
                        .WithMany("Items")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSSVibe.Data.Entities.FeedParseRun", "FirstParseRun")
                        .WithMany()
                        .HasForeignKey("FirstParseRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RSSVibe.Data.Entities.FeedParseRun", "LastParseRun")
                        .WithMany()
                        .HasForeignKey("LastParseRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Feed");

                    b.Navigation("FirstParseRun");

                    b.Navigation("LastParseRun");
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.FeedParseRun", b =>
                {
                    b.HasOne("RSSVibe.Data.Entities.Feed", "Feed")
                        .WithMany("ParseRuns")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.FeedParseRunItem", b =>
                {
                    b.HasOne("RSSVibe.Data.Entities.FeedItem", "FeedItem")
                        .WithMany("ParseRunItems")
                        .HasForeignKey("FeedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSSVibe.Data.Entities.FeedParseRun", "FeedParseRun")
                        .WithMany("ParseRunItems")
                        .HasForeignKey("FeedParseRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedItem");

                    b.Navigation("FeedParseRun");
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("RSSVibe.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.Feed", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("ParseRuns");
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.FeedAnalysis", b =>
                {
                    b.Navigation("ApprovedFeed");
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.FeedItem", b =>
                {
                    b.Navigation("ParseRunItems");
                });

            modelBuilder.Entity("RSSVibe.Data.Entities.FeedParseRun", b =>
                {
                    b.Navigation("ParseRunItems");
                });
#pragma warning restore 612, 618
        }
    }
}
